### ISSUE TITLE
Help to package on Debian

### ISSUE THREAD

**Issue by yuzibo** [marzer/poxy#16]
Hi,
I am working to package this module into Debian, I just want to confirm it here:
There is misk>=0.7.0 in requirements.txt, the misk is this [misk](https://github.com/marzer/misk)?
Because the misk does not come into Debian also,if so, I have to package it first, thanks.

**Comment by marzer** [comment]
@bgermann 

> There are already enough Python TOML parsers in Debian...

Who cares? Are packages somehow a finite resource? Pretty weird request tbh.

**Comment by bgermann** [comment]
No, not packages but package maintainers...

**Comment by marzer** [comment]
@bgermann That sounds like a problem with the debian ecosystem, not with me. 

Some points:
- Neither `tomli` or `tomllib` support serializing TOML; poxy does not currently need that feature but I have the idea to support a config generation/updating feature in future and may wish to serialize TOML at that time.
- `pytomlpp` is based on C++'s [`toml++`], rather than being pure python, making it very fast.
	- Incidentally, _I am the author of [`toml++`]_; you're effectively telling me my library isn't worthy of being packaged for the sanctified territory that is Debian, so piss off with that.
- All of this is moot anyway; `poxy` is meant to be installed via `pip`; having it as a separate debian package does not seem to add any value, so I'm not making nontrivial changes for that.

[`toml++`]: https://github.com/marzer/tomlplusplus

**Comment by bgermann** [comment]
I am not telling you your package is not worthy of some kind. No need to piss anyone off. It was just a comment about what would make this endeavour faster.

**Comment by bgermann** [comment]
And I did not say it was your problem.

**Comment by bgermann** [comment]
No, I did not ask you to do anything. Maybe accept a pull request when someone has done the work.

**Comment by marzer** [comment]
Ok so was 

> It would be helpful to depend on tomli (or Python 3.11's tomllib) instead of pytomlpp. There are already enough Python TOML parsers in Debian...

Not meant for me? Are you just 'putting that out there' so someone else will actions it? If someone submits a PR to make that change, I will reject it.

**Comment by bgermann** [comment]
Okay, fine.
