### ISSUE TITLE
Enable USE_MATHJAX = TRUE

### ISSUE THREAD

**Issue by taehyounpark** [marzer/poxy#35]
First of all, thank you for this repository! I've looked for everything under the sun for something that would *actually* handle Doxygen documentation for highly-templated code, only to run into confusing quirks at best or even flat-out erroneous output from several other workflows. m.css together with poxy, gets it *perfect*!

I just wanted to ask/request how one might be able to insert math equations into the markdown files? As far as I understand, this requires [USE_MATHJAX](http://www.doxygen.nl/manual/config.html#cfg_use_mathjax) option which is by default false, and poxy (as stated in README) does not allow configs to be changed manually.

Would such an option being allowed in `poxy.toml` cause any issues with the current locked-down Doxygen configuration? Thanks again in advance!

**Comment by marzer** [comment]
Hiya,

> Would such an option being allowed in poxy.toml cause any issues with the current locked-down Doxygen configuration?

I suspect it would be fine. My choice to lock down the config mostly just to limit the chaos that doxygen can actually cause, since their testing process is lacking and there are always many regressions from one version to the next.

I don't have strong opinions on most of the available options - I just by disabled things I personally didn't want when I started wrapping things up in Poxy as a starting point :)

It only depends on whether m.css supports this particular thing, since poxy doesn't do much in the way of HTML rendering (only minor bugfixes and small features using pre- and post- processes).

**Comment by marzer** [comment]
Ah ok so m.css provides support for math formulas but it does not appear to be based on the Doxygen option USE_MATHJAX option, since that requires you to using Doxygen's `GENERATE_HTML` option, which isn't the case (m.css handles HTML rendering itself using doxygen's XML output mode instead).

Have a look at the math-related information in the [m.css Doxygen generator documentation](https://mcss.mosra.cz/documentation/doxygen/); you might find this already works without needing any extra work :)

**Comment by taehyounpark** [comment]
You are right and `@f$ x+y @f$` works out of the box the irony of not having read the documentation :sweat_smile: thanks!

**Comment by mosra** [comment]
Haha, yes, it's builtin and should "just work", if you have a LaTeX installation set up.

Some background info -- one of the reasons I started making the m.css theme in the first place was because I _hated_ how math equations looked like on most websites, either being blurry / aliased raster images, or flickering and causing page relayouts because it was rendered by some heavy JavaScript on the client side.

So it's instead rendered into a SVG which is then embedded directly into the markup. Here's a "marketing page" for it back from 2018, most / all features shown there including the window-size-dependent layout are possible with Doxygen and the custom `@m_class` command as well: https://mcss.mosra.cz/admire/math/

**Comment by lucasmyers97** [comment]
One follow-up on this: is it possible to use the markdown math syntax (i.e. enclosing `$` or ```math blocks) and still use the m.css functionality? I ask with the aim of using a README.md both as a GitHub front page, and the front page of the poxy-generated documentation.

**Comment by mosra** [comment]
If Doxygen itself supports that (which is a GitHub Flawored Markdown extension I think) and correctly passes that to the generated XML, m.css will as well.

There has been a new 1.11 release yesterday, but I can't see anything latex-math-specific in the changelogs. Maybe it's already there, I never really tried. (Also no idea how crashy or buggy it is, I [didn't even manage to get 1.9 running properly for my code yet](https://github.com/mosra/m.css/issues/215).)
